version: "3.9"
services:
  db:
    image: postgres:12.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
  tests:
    image: vnovitskyi/assignment-kittens-store
    command: [ 'sh', 'run_tests.sh' ]
    depends_on:
      - db
    environment:
      RAILS_ENV: tests
      DATABASE_URL: postgres://postgres_user:postgres_pass@db:5432/kittens_store_test
  app:
    image: vnovitskyi/assignment-kittens-store
    ports:
      - "1234:1234"
    command: ['sh', 'run_app.sh']
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres_user:postgres_pass@db:5432/kittens_store_dev