apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: kitten-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
      name: http