apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          command:
            - bundle
            - exec
            - rake
            - db:create
            - db:migrate
            - db:seed
          image: vnovitskyi/assignment-kittens-store
          env:
            - name: RACK_ENV
              value: development
            - name: DATABASE_URL
              value: postgres://app:pass@postgresql-service:5432