apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-app-service
  labels:
    environment: {{ .Values.envvars.rack_env }}
spec:
  selector:
    app: {{ .Values.app.name }}-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.webserver.port }}
      name: http