app:
  name: kittens
envvars:
  database_url: postgres://postgres:YT4FLkTUEIcBpRqf@kittens-rds20210903120039053200000007.ckh7xfijjfey.eu-central-1.rds.amazonaws.com:5432/kittens_dev
  rack_env: development

postgress:
  enabled: false

image:
  repository: vnovitskyi/assignment-kittens-store

webserver:
  replicaCount: 1
  command: "bundle exec rackup --port 1234 --host 0.0.0.0"
  port: 1234

migrations:
  command: "bundle exec rake db:create db:migrate db:seed"