app:
  name: kittens
envvars:
  database_url: postgres://app:pass@postgresql-service:5432
  rack_env: development

image:
  repository: vnovitskyi/assignment-kittens-store

webserver:
  replicaCount: 1
  command: "bundle exec rackup --port 1234 --host 0.0.0.0"
  port: 1234

migrations:
  command: "bundle exec rake db:create db:migrate db:seed"