name: CD

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

env:
  AWS_REGION: eu-central-1
  CLUSTER_NAME: eks-1
  
jobs:
  publish:
    name: "Release to AWS"
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2.3.4
        
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: master
          running-workflow-name: 'Release to AWS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +'%Y-%m-%d')
          nm=${{ github.run_number }}
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}-${nm}"

      - name: Build & push Docker image to Dockerhub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: vnovitskyi/assignment-kittens-store
          registry: docker.io
          tags: ${{ steps.prep.outputs.BUILD_ID }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Configure AWS client
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name:  Login to cluster
        run: >
          aws eks update-kubeconfig
          --region ${AWS_REGION}
          --name ${CLUSTER_NAME}
          
      - name:  Test cluster access
        run: kubectl get nodes
