name: "destroy infrastructure"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  cleanup-infrastructure:
    name: "Infrastructure destroy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Delete all of the remaining balancers using AWS CLI
        run: aws elb describe-load-balancers | jq '.LoadBalancerDescriptions | .[] | .LoadBalancerName' | xargs -L1 aws elb delete-load-balancer --load-balancer-name

      - name: Terraform Init
        id: init
        run: terraform -chdir=ops/tf/global/ init

      - name: Terraform Destroy
        id: destroy
        run: terraform -chdir=ops/tf/global/ destroy -auto-approve

      - name: Delete all of the remaining balancers using AWS CLI
        run: aws elb describe-load-balancers | jq '.LoadBalancerDescriptions | .[] | .LoadBalancerName' | xargs -L1 aws elb delete-load-balancer --load-balancer-name