name: CD

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: vnovitskyi/assignment-kittens-store
          registry: docker.io
          tags: v1.0
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
